CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    birthdate DATE NOT NULL,
    balance NUMERIC(15, 2) NOT NULL DEFAULT 0
    );