server:
  port: 8084

spring:
  application:
    name: transfer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: transfer
      config:
        enabled: true
        defaultContext: application
        prefixes: config

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
        registration:
          service-client:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: transfer-service
            client-secret: 5uTr3jD2Kxzx1kBndipRszZwYZ6V8ub5
#            client-secret: ${KEYCLOAK_TRANSFER_CLIENT_SECRET}
            scope: internal

logging:
  level:
    root: info
    ru.practicum: debug