server:
  port: 8084

spring:
  config:
    import: "optional:consul:"
  application:
    name: transfer
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: transfer
      config:
        enabled: true
        defaultContext: application
        prefixes: config

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bank/protocol/openid-connect/token
        registration:
          service-client:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: transfer-service
#            client-secret: ${KEYCLOAK_TRANSFER_CLIENT_SECRET}
            client-secret: PYtSUAbgQq5ljGaQYktElzZxqxPBo7hE
            scope: internal

logging:
  level:
    root: info
    ru.practicum: debug