server:
  port: 8083

spring:
  config:
    import: "optional:consul:"
  application:
    name: cash
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: cash
      config:
        enabled: true
        defaultContext: application
        prefixes: config

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bank/protocol/openid-connect/token
        registration:
          service-client:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: cash-service
            client-secret: ZTF26gIc846BAtUD1wZDnCy5U2tyIuSS
            scope: internal

logging:
  level:
    root: info
    ru.practicum: debug